function plotMechanicalCombinedStressCurves(experiment, saveFolder)
% Plots combined median stress-strain curves with bootstrap intervals.
% Annotates the median modulus for each condition.
%
% Inputs:
%   experiment - Structure containing processed mechanical test data.
%   saveFolder - Folder where figures are saved.
%
% Outputs:
%   Saves one combined .fig and .tif figure.

    ensureFolderExists(saveFolder);

    settings = experiment.settings;
    labels = experiment.labels;

    figHandle = createWhiteFigure();
    hold on;

    title(['Combined median ' lower(labels.testName) ...
        ' stress-strain curves with bootstrap CI and modulus']);

    xlabel(labels.strain);
    ylabel(labels.stress);

    colors = lines(numel(experiment.conditions));

    for f = 1:numel(experiment.conditions)

        condition = experiment.conditions(f);
        c = colors(f,:);

        fill([condition.common_strain fliplr(condition.common_strain)], ...
             [condition.upper_stress_CI' fliplr(condition.lower_stress_CI')], ...
             c, ...
             'FaceAlpha', 0.25, ...
             'EdgeColor', 'none', ...
             'DisplayName', [num2str(settings.ci_level) '% bootstrap CI ' condition.name]);

        plot(condition.common_strain, condition.median_stress, ...
             'Color', c, ...
             'LineWidth', 1.5, ...
             'DisplayName', condition.name);

        idx_end_modulus = min(settings.i_samples + settings.E_window_samples - 1, ...
            length(condition.common_strain));

        if idx_end_modulus > settings.i_samples

            plot(condition.common_strain(settings.i_samples:idx_end_modulus), ...
                 condition.median_stress(settings.i_samples:idx_end_modulus), ...
                 'Color', c, ...
                 'LineWidth', 2.5, ...
                 'LineStyle', '--', ...
                 'DisplayName', ['Modulus interval ' condition.name]);

            mid_idx = round((settings.i_samples + idx_end_modulus)/2);

            text(condition.common_strain(mid_idx), ...
                 condition.median_stress(mid_idx), ...
                 sprintf('%s = %.2f [%.2f, %.2f] MPa', ...
                 labels.modulusSymbol, condition.E_median, ...
                 condition.E_lower_CI, condition.E_upper_CI), ...
                 'Color', c, ...
                 'FontWeight', 'bold', ...
                 'FontSize', 8, ...
                 'BackgroundColor', 'w', ...
                 'Margin', 1, ...
                 'HorizontalAlignment', 'center', ...
                 'VerticalAlignment', 'bottom');
        end
    end

    legend('show', 'Location', 'best');
    hold off;

    saveFigureBothFormats(figHandle, saveFolder, ...
        [experiment.testType '_combined_median_stress_strain']);
end