function outputFiles = exportFitUncertainty(fitResult, uncertainty, outputFolder)
%EXPORTFITUNCERTAINTY Export bootstrap uncertainty tables and MAT data.
arguments
    fitResult (1,1) struct
    uncertainty (1,1) struct
    outputFolder (1,1) string
end

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

parameterTable = table( ...
    uncertainty.parameterNames(:), ...
    uncertainty.baseParameters(:), ...
    uncertainty.parameterMedian(:), ...
    uncertainty.parameterLower(:), ...
    uncertainty.parameterUpper(:), ...
    'VariableNames', { ...
        'Parameter', 'BestFit', 'BootstrapMedian', ...
        'ConfidenceLower', 'ConfidenceUpper'});

predictionTable = table( ...
    uncertainty.predictionDeformation(:), ...
    uncertainty.predictionMedian(:), ...
    uncertainty.predictionLower(:), ...
    uncertainty.predictionUpper(:), ...
    'VariableNames', { ...
        'Deformation', 'BootstrapMedian', ...
        'ConfidenceLower', 'ConfidenceUpper'});

parameterFile = fullfile(outputFolder, "parameter_uncertainty.csv");
predictionFile = fullfile(outputFolder, "prediction_uncertainty.csv");
dataFile = fullfile(outputFolder, "fit_uncertainty.mat");

writetable(parameterTable, parameterFile);
writetable(predictionTable, predictionFile);
save(dataFile, "fitResult", "uncertainty");

outputFiles.parameters = string(parameterFile);
outputFiles.predictions = string(predictionFile);
outputFiles.data = string(dataFile);
end
