function figureHandle = plotPopulationStressStrain(population)
%PLOTPOPULATIONSTRESSSTRAIN Plot replicate curves and aggregate statistics.
arguments
    population (1,1) struct
end

aggregate = population.curves;

figureHandle = figure("Color", "w");
axesHandle = axes(figureHandle);
hold(axesHandle, "on");

for index = 1:size(aggregate.stressMatrix, 2)
    plot(axesHandle, ...
        aggregate.strain, ...
        aggregate.stressMatrix(:, index), ...
        "LineWidth", 0.8, ...
        "HandleVisibility", "off");
end

if all(isfinite(aggregate.confidenceLower)) && ...
        all(isfinite(aggregate.confidenceUpper))
    xValues = [aggregate.strain; flipud(aggregate.strain)];
    yValues = [ ...
        aggregate.confidenceLower; ...
        flipud(aggregate.confidenceUpper)];

    fill(axesHandle, xValues, yValues, 0.8 .* [1, 1, 1], ...
        "EdgeColor", "none", ...
        "FaceAlpha", 0.5, ...
        "DisplayName", sprintf( ...
            "%.0f%% bootstrap CI", ...
            100 .* aggregate.config.bootstrap.confidenceLevel));
end

plot(axesHandle, ...
    aggregate.strain, ...
    aggregate.meanStress, ...
    "LineWidth", 2, ...
    "DisplayName", "Mean");

xlabel(axesHandle, "Strain");
ylabel(axesHandle, "Stress");
grid(axesHandle, "on");
box(axesHandle, "on");
legend(axesHandle, "Location", "best");
end
