function summary = summarizeWindowStability(study)
%SUMMARIZEWINDOWSTABILITY Summarize fit quality and parameter stability.
arguments
    study (1,1) struct
end

modelNames = study.modelNames(:);
selectionConfig = study.selectionConfig;
nModels = numel(modelNames);

model = strings(nModels,1);
windowCount = zeros(nModels,1);
successfulWindowCount = zeros(nModels,1);
convergedWindowCount = zeros(nModels,1);
fullWindowParameterCount = nan(nModels,1);
fullWindowRMSE = nan(nModels,1);
fullWindowRSquared = nan(nModels,1);
fullWindowAIC = nan(nModels,1);
fullWindowBIC = nan(nModels,1);
maximumRelativeParameterCV = nan(nModels,1);
parameterStable = false(nModels,1);
eligible = false(nModels,1);

parameterMeans = cell(nModels,1);
parameterStd = cell(nModels,1);
parameterCV = cell(nModels,1);
parameterNames = cell(nModels,1);

for iModel = 1:nModels
    model(iModel) = modelNames(iModel);
    records = study.records([study.records.modelName] == modelNames(iModel));
    windowCount(iModel) = numel(records);

    successMask = [records.succeeded];
    successful = records(successMask);
    successfulWindowCount(iModel) = numel(successful);

    if isempty(successful)
        continue;
    end

    convergedMask = arrayfun(@(r) r.fitResult.converged, successful);
    convergedWindowCount(iModel) = nnz(convergedMask);

    fractions = [successful.windowFraction];
    [~, fullIndex] = max(fractions);
    fullResult = successful(fullIndex).fitResult;
    fullWindowParameterCount(iModel) = fullResult.metrics.parameterCount;
    fullWindowRMSE(iModel) = fullResult.metrics.rmse;
    fullWindowRSquared(iModel) = fullResult.metrics.rSquared;
    fullWindowAIC(iModel) = fullResult.metrics.aic;
    fullWindowBIC(iModel) = fullResult.metrics.bic;

    parameterNames{iModel} = fullResult.parameterNames(:)';
    parameterMatrix = vertcat(successful.fitResult);
    parameterMatrix = vertcat(parameterMatrix.parameters);

    means = mean(parameterMatrix, 1);
    standardDeviations = std(parameterMatrix, 0, 1);
    scales = max(abs(means), selectionConfig.relativeScaleFloor);
    cvs = standardDeviations ./ scales;

    parameterMeans{iModel} = means;
    parameterStd{iModel} = standardDeviations;
    parameterCV{iModel} = cvs;
    maximumRelativeParameterCV(iModel) = max(cvs);

    parameterStable(iModel) = all(isfinite(cvs)) && ...
        maximumRelativeParameterCV(iModel) <= ...
        selectionConfig.maximumRelativeParameterCV;

    hasAllWindows = successfulWindowCount(iModel) == windowCount(iModel);
    convergenceAccepted = ~selectionConfig.requireConvergence || ...
        convergedWindowCount(iModel) == successfulWindowCount(iModel);

    eligible(iModel) = hasAllWindows && convergenceAccepted && ...
        parameterStable(iModel) && isfinite(fullWindowBIC(iModel));
end

summary = table( ...
    model, ...
    windowCount, ...
    successfulWindowCount, ...
    convergedWindowCount, ...
    fullWindowParameterCount, ...
    fullWindowRMSE, ...
    fullWindowRSquared, ...
    fullWindowAIC, ...
    fullWindowBIC, ...
    maximumRelativeParameterCV, ...
    parameterStable, ...
    eligible, ...
    parameterNames, ...
    parameterMeans, ...
    parameterStd, ...
    parameterCV, ...
    'VariableNames', { ...
        'Model', ...
        'WindowCount', ...
        'SuccessfulWindowCount', ...
        'ConvergedWindowCount', ...
        'FullWindowParameterCount', ...
        'FullWindowRMSE', ...
        'FullWindowRSquared', ...
        'FullWindowAIC', ...
        'FullWindowBIC', ...
        'MaximumRelativeParameterCV', ...
        'ParameterStable', ...
        'Eligible', ...
        'ParameterNames', ...
        'ParameterMeans', ...
        'ParameterStd', ...
        'ParameterCV'});
end
